### ISSUE TITLE
[Question] Is it possible to use an application.yml instead of properties file? 

### ISSUE THREAD

**Issue by munichbughunter** [mstykt/gauge-demo#1]
Hi, 

I found your cool demo repo via the medium article. 

I have a question. 
Is it possible to change the properties file with an application.yml? 

I didn`t found a way to do that.

**Comment by mstykt** [comment]
Hi,

In gauge projects, context works with gauge specifications. As you can see we don't use main method in our GaugeDemoApp.class, just annotated with '@SpringBootApplication'. The main purpose is that take beans from spring and auto config with springboot. If you want to use application.yml or any other file even directory, gauge provides some options, you can check them on official document. 

Info about config: [gauge doc](https://docs.gauge.org/configuration.html?os=macos&language=java&ide=intellij)
